/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package replicationsubnetgroup

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/databasemigrationservice"

	svcapitypes "github.com/crossplane/provider-aws/apis/databasemigrationservice/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateDescribeReplicationSubnetGroupsInput returns input for read
// operation.
func GenerateDescribeReplicationSubnetGroupsInput(cr *svcapitypes.ReplicationSubnetGroup) *svcsdk.DescribeReplicationSubnetGroupsInput {
	res := &svcsdk.DescribeReplicationSubnetGroupsInput{}

	return res
}

// GenerateReplicationSubnetGroup returns the current state in the form of *svcapitypes.ReplicationSubnetGroup.
func GenerateReplicationSubnetGroup(resp *svcsdk.DescribeReplicationSubnetGroupsOutput) *svcapitypes.ReplicationSubnetGroup {
	cr := &svcapitypes.ReplicationSubnetGroup{}

	found := false
	for _, elem := range resp.ReplicationSubnetGroups {
		if elem.ReplicationSubnetGroupDescription != nil {
			cr.Spec.ForProvider.ReplicationSubnetGroupDescription = elem.ReplicationSubnetGroupDescription
		} else {
			cr.Spec.ForProvider.ReplicationSubnetGroupDescription = nil
		}
		if elem.ReplicationSubnetGroupIdentifier != nil {
			cr.Spec.ForProvider.ReplicationSubnetGroupIdentifier = elem.ReplicationSubnetGroupIdentifier
		} else {
			cr.Spec.ForProvider.ReplicationSubnetGroupIdentifier = nil
		}
		if elem.SubnetGroupStatus != nil {
			cr.Status.AtProvider.SubnetGroupStatus = elem.SubnetGroupStatus
		} else {
			cr.Status.AtProvider.SubnetGroupStatus = nil
		}
		if elem.Subnets != nil {
			f3 := []*svcapitypes.Subnet{}
			for _, f3iter := range elem.Subnets {
				f3elem := &svcapitypes.Subnet{}
				if f3iter.SubnetAvailabilityZone != nil {
					f3elemf0 := &svcapitypes.AvailabilityZone{}
					if f3iter.SubnetAvailabilityZone.Name != nil {
						f3elemf0.Name = f3iter.SubnetAvailabilityZone.Name
					}
					f3elem.SubnetAvailabilityZone = f3elemf0
				}
				if f3iter.SubnetIdentifier != nil {
					f3elem.SubnetIdentifier = f3iter.SubnetIdentifier
				}
				if f3iter.SubnetStatus != nil {
					f3elem.SubnetStatus = f3iter.SubnetStatus
				}
				f3 = append(f3, f3elem)
			}
			cr.Status.AtProvider.Subnets = f3
		} else {
			cr.Status.AtProvider.Subnets = nil
		}
		if elem.VpcId != nil {
			cr.Status.AtProvider.VPCID = elem.VpcId
		} else {
			cr.Status.AtProvider.VPCID = nil
		}
		found = true
		break
	}
	if !found {
		return cr
	}

	return cr
}

// GenerateCreateReplicationSubnetGroupInput returns a create input.
func GenerateCreateReplicationSubnetGroupInput(cr *svcapitypes.ReplicationSubnetGroup) *svcsdk.CreateReplicationSubnetGroupInput {
	res := &svcsdk.CreateReplicationSubnetGroupInput{}

	if cr.Spec.ForProvider.ReplicationSubnetGroupDescription != nil {
		res.SetReplicationSubnetGroupDescription(*cr.Spec.ForProvider.ReplicationSubnetGroupDescription)
	}
	if cr.Spec.ForProvider.ReplicationSubnetGroupIdentifier != nil {
		res.SetReplicationSubnetGroupIdentifier(*cr.Spec.ForProvider.ReplicationSubnetGroupIdentifier)
	}
	if cr.Spec.ForProvider.SubnetIDs != nil {
		f2 := []*string{}
		for _, f2iter := range cr.Spec.ForProvider.SubnetIDs {
			var f2elem string
			f2elem = *f2iter
			f2 = append(f2, &f2elem)
		}
		res.SetSubnetIds(f2)
	}
	if cr.Spec.ForProvider.Tags != nil {
		f3 := []*svcsdk.Tag{}
		for _, f3iter := range cr.Spec.ForProvider.Tags {
			f3elem := &svcsdk.Tag{}
			if f3iter.Key != nil {
				f3elem.SetKey(*f3iter.Key)
			}
			if f3iter.Value != nil {
				f3elem.SetValue(*f3iter.Value)
			}
			f3 = append(f3, f3elem)
		}
		res.SetTags(f3)
	}

	return res
}

// GenerateModifyReplicationSubnetGroupInput returns an update input.
func GenerateModifyReplicationSubnetGroupInput(cr *svcapitypes.ReplicationSubnetGroup) *svcsdk.ModifyReplicationSubnetGroupInput {
	res := &svcsdk.ModifyReplicationSubnetGroupInput{}

	if cr.Spec.ForProvider.ReplicationSubnetGroupDescription != nil {
		res.SetReplicationSubnetGroupDescription(*cr.Spec.ForProvider.ReplicationSubnetGroupDescription)
	}
	if cr.Spec.ForProvider.ReplicationSubnetGroupIdentifier != nil {
		res.SetReplicationSubnetGroupIdentifier(*cr.Spec.ForProvider.ReplicationSubnetGroupIdentifier)
	}
	if cr.Spec.ForProvider.SubnetIDs != nil {
		f2 := []*string{}
		for _, f2iter := range cr.Spec.ForProvider.SubnetIDs {
			var f2elem string
			f2elem = *f2iter
			f2 = append(f2, &f2elem)
		}
		res.SetSubnetIds(f2)
	}

	return res
}

// GenerateDeleteReplicationSubnetGroupInput returns a deletion input.
func GenerateDeleteReplicationSubnetGroupInput(cr *svcapitypes.ReplicationSubnetGroup) *svcsdk.DeleteReplicationSubnetGroupInput {
	res := &svcsdk.DeleteReplicationSubnetGroupInput{}

	if cr.Spec.ForProvider.ReplicationSubnetGroupIdentifier != nil {
		res.SetReplicationSubnetGroupIdentifier(*cr.Spec.ForProvider.ReplicationSubnetGroupIdentifier)
	}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN"
}
