/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AuthMechanismValue string

const (
	AuthMechanismValue_default     AuthMechanismValue = "default"
	AuthMechanismValue_mongodb_cr  AuthMechanismValue = "mongodb_cr"
	AuthMechanismValue_scram_sha_1 AuthMechanismValue = "scram_sha_1"
)

type AuthTypeValue string

const (
	AuthTypeValue_no       AuthTypeValue = "no"
	AuthTypeValue_password AuthTypeValue = "password"
)

type CharLengthSemantics string

const (
	CharLengthSemantics_default CharLengthSemantics = "default"
	CharLengthSemantics_char    CharLengthSemantics = "char"
	CharLengthSemantics_byte    CharLengthSemantics = "byte"
)

type CompressionTypeValue string

const (
	CompressionTypeValue_none CompressionTypeValue = "none"
	CompressionTypeValue_gzip CompressionTypeValue = "gzip"
)

type DataFormatValue string

const (
	DataFormatValue_csv     DataFormatValue = "csv"
	DataFormatValue_parquet DataFormatValue = "parquet"
)

type DatePartitionDelimiterValue string

const (
	DatePartitionDelimiterValue_SLASH      DatePartitionDelimiterValue = "SLASH"
	DatePartitionDelimiterValue_UNDERSCORE DatePartitionDelimiterValue = "UNDERSCORE"
	DatePartitionDelimiterValue_DASH       DatePartitionDelimiterValue = "DASH"
	DatePartitionDelimiterValue_NONE       DatePartitionDelimiterValue = "NONE"
)

type DatePartitionSequenceValue string

const (
	DatePartitionSequenceValue_YYYYMMDD   DatePartitionSequenceValue = "YYYYMMDD"
	DatePartitionSequenceValue_YYYYMMDDHH DatePartitionSequenceValue = "YYYYMMDDHH"
	DatePartitionSequenceValue_YYYYMM     DatePartitionSequenceValue = "YYYYMM"
	DatePartitionSequenceValue_MMYYYYDD   DatePartitionSequenceValue = "MMYYYYDD"
	DatePartitionSequenceValue_DDMMYYYY   DatePartitionSequenceValue = "DDMMYYYY"
)

type DmsSSLModeValue string

const (
	DmsSSLModeValue_none        DmsSSLModeValue = "none"
	DmsSSLModeValue_require     DmsSSLModeValue = "require"
	DmsSSLModeValue_verify_ca   DmsSSLModeValue = "verify-ca"
	DmsSSLModeValue_verify_full DmsSSLModeValue = "verify-full"
)

type EncodingTypeValue string

const (
	EncodingTypeValue_plain            EncodingTypeValue = "plain"
	EncodingTypeValue_plain_dictionary EncodingTypeValue = "plain-dictionary"
	EncodingTypeValue_rle_dictionary   EncodingTypeValue = "rle-dictionary"
)

type EncryptionModeValue string

const (
	EncryptionModeValue_sse_s3  EncryptionModeValue = "sse-s3"
	EncryptionModeValue_sse_kms EncryptionModeValue = "sse-kms"
)

type MessageFormatValue string

const (
	MessageFormatValue_json             MessageFormatValue = "json"
	MessageFormatValue_json_unformatted MessageFormatValue = "json-unformatted"
)

type MigrationTypeValue string

const (
	MigrationTypeValue_full_load         MigrationTypeValue = "full-load"
	MigrationTypeValue_cdc               MigrationTypeValue = "cdc"
	MigrationTypeValue_full_load_and_cdc MigrationTypeValue = "full-load-and-cdc"
)

type NestingLevelValue string

const (
	NestingLevelValue_none NestingLevelValue = "none"
	NestingLevelValue_one  NestingLevelValue = "one"
)

type ParquetVersionValue string

const (
	ParquetVersionValue_parquet_1_0 ParquetVersionValue = "parquet-1-0"
	ParquetVersionValue_parquet_2_0 ParquetVersionValue = "parquet-2-0"
)

type RefreshSchemasStatusTypeValue string

const (
	RefreshSchemasStatusTypeValue_successful RefreshSchemasStatusTypeValue = "successful"
	RefreshSchemasStatusTypeValue_failed     RefreshSchemasStatusTypeValue = "failed"
	RefreshSchemasStatusTypeValue_refreshing RefreshSchemasStatusTypeValue = "refreshing"
)

type ReleaseStatusValues string

const (
	ReleaseStatusValues_beta ReleaseStatusValues = "beta"
)

type ReloadOptionValue string

const (
	ReloadOptionValue_data_reload   ReloadOptionValue = "data-reload"
	ReloadOptionValue_validate_only ReloadOptionValue = "validate-only"
)

type ReplicationEndpointTypeValue string

const (
	ReplicationEndpointTypeValue_source ReplicationEndpointTypeValue = "source"
	ReplicationEndpointTypeValue_target ReplicationEndpointTypeValue = "target"
)

type SafeguardPolicy string

const (
	SafeguardPolicy_rely_on_sql_server_replication_agent SafeguardPolicy = "rely-on-sql-server-replication-agent"
	SafeguardPolicy_exclusive_automatic_truncation       SafeguardPolicy = "exclusive-automatic-truncation"
	SafeguardPolicy_shared_automatic_truncation          SafeguardPolicy = "shared-automatic-truncation"
)

type SourceType string

const (
	SourceType_replication_instance SourceType = "replication-instance"
)

type StartReplicationTaskTypeValue string

const (
	StartReplicationTaskTypeValue_start_replication StartReplicationTaskTypeValue = "start-replication"
	StartReplicationTaskTypeValue_resume_processing StartReplicationTaskTypeValue = "resume-processing"
	StartReplicationTaskTypeValue_reload_target     StartReplicationTaskTypeValue = "reload-target"
)

type TargetDBType string

const (
	TargetDBType_specific_database  TargetDBType = "specific-database"
	TargetDBType_multiple_databases TargetDBType = "multiple-databases"
)
