/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
)

type AccountQuota struct {
	AccountQuotaName *string `json:"accountQuotaName,omitempty"`
}

type AvailabilityZone struct {
	Name *string `json:"name,omitempty"`
}

type Certificate struct {
	CertificateARN *string `json:"certificateARN,omitempty"`

	CertificateIdentifier *string `json:"certificateIdentifier,omitempty"`

	CertificateOwner *string `json:"certificateOwner,omitempty"`

	CertificatePem *string `json:"certificatePem,omitempty"`

	KeyLength *int64 `json:"keyLength,omitempty"`

	SigningAlgorithm *string `json:"signingAlgorithm,omitempty"`
}

type Connection struct {
	EndpointARN *string `json:"endpointARN,omitempty"`

	EndpointIdentifier *string `json:"endpointIdentifier,omitempty"`

	LastFailureMessage *string `json:"lastFailureMessage,omitempty"`

	ReplicationInstanceARN *string `json:"replicationInstanceARN,omitempty"`

	ReplicationInstanceIdentifier *string `json:"replicationInstanceIdentifier,omitempty"`

	Status *string `json:"status,omitempty"`
}

type DmsTransferSettings struct {
	BucketName *string `json:"bucketName,omitempty"`

	ServiceAccessRoleARN *string `json:"serviceAccessRoleARN,omitempty"`
}

type DocDBSettings struct {
	DatabaseName *string `json:"databaseName,omitempty"`

	DocsToInvestigate *int64 `json:"docsToInvestigate,omitempty"`

	KMSKeyID *string `json:"kmsKeyID,omitempty"`

	Port *int64 `json:"port,omitempty"`

	SecretsManagerAccessRoleARN *string `json:"secretsManagerAccessRoleARN,omitempty"`

	SecretsManagerSecretID *string `json:"secretsManagerSecretID,omitempty"`

	ServerName *string `json:"serverName,omitempty"`

	Username *string `json:"username,omitempty"`
}

type DynamoDBSettings struct {
	ServiceAccessRoleARN *string `json:"serviceAccessRoleARN,omitempty"`
}

type ElasticsearchSettings struct {
	EndpointURI *string `json:"endpointURI,omitempty"`

	ErrorRetryDuration *int64 `json:"errorRetryDuration,omitempty"`

	FullLoadErrorPercentage *int64 `json:"fullLoadErrorPercentage,omitempty"`

	ServiceAccessRoleARN *string `json:"serviceAccessRoleARN,omitempty"`
}

type Endpoint struct {
	CertificateARN *string `json:"certificateARN,omitempty"`

	DatabaseName *string `json:"databaseName,omitempty"`

	EndpointARN *string `json:"endpointARN,omitempty"`

	EndpointIdentifier *string `json:"endpointIdentifier,omitempty"`

	EngineDisplayName *string `json:"engineDisplayName,omitempty"`

	EngineName *string `json:"engineName,omitempty"`

	ExternalID *string `json:"externalID,omitempty"`

	ExternalTableDefinition *string `json:"externalTableDefinition,omitempty"`

	ExtraConnectionAttributes *string `json:"extraConnectionAttributes,omitempty"`

	KMSKeyID *string `json:"kmsKeyID,omitempty"`

	Port *int64 `json:"port,omitempty"`

	ServerName *string `json:"serverName,omitempty"`

	ServiceAccessRoleARN *string `json:"serviceAccessRoleARN,omitempty"`

	Status *string `json:"status,omitempty"`

	Username *string `json:"username,omitempty"`
}

type Event struct {
	Message *string `json:"message,omitempty"`

	SourceIdentifier *string `json:"sourceIdentifier,omitempty"`
}

type EventCategoryGroup struct {
	SourceType *string `json:"sourceType,omitempty"`
}

type EventSubscription struct {
	CustSubscriptionID *string `json:"custSubscriptionID,omitempty"`

	CustomerAWSID *string `json:"customerAWSID,omitempty"`

	SnsTopicARN *string `json:"snsTopicARN,omitempty"`

	SourceType *string `json:"sourceType,omitempty"`

	Status *string `json:"status,omitempty"`

	SubscriptionCreationTime *string `json:"subscriptionCreationTime,omitempty"`
}

type Filter struct {
	Name *string `json:"name,omitempty"`

	Values []*string `json:"values,omitempty"`
}

type IBMDB2Settings struct {
	CurrentLsn *string `json:"currentLsn,omitempty"`

	DatabaseName *string `json:"databaseName,omitempty"`

	MaxKBytesPerRead *int64 `json:"maxKBytesPerRead,omitempty"`

	Port *int64 `json:"port,omitempty"`

	SecretsManagerAccessRoleARN *string `json:"secretsManagerAccessRoleARN,omitempty"`

	SecretsManagerSecretID *string `json:"secretsManagerSecretID,omitempty"`

	ServerName *string `json:"serverName,omitempty"`

	Username *string `json:"username,omitempty"`
}

type KafkaSettings struct {
	Broker *string `json:"broker,omitempty"`

	MessageMaxBytes *int64 `json:"messageMaxBytes,omitempty"`

	Topic *string `json:"topic,omitempty"`
}

type KinesisSettings struct {
	ServiceAccessRoleARN *string `json:"serviceAccessRoleARN,omitempty"`

	StreamARN *string `json:"streamARN,omitempty"`
}

type MicrosoftSQLServerSettings struct {
	BcpPacketSize *int64 `json:"bcpPacketSize,omitempty"`

	ControlTablesFileGroup *string `json:"controlTablesFileGroup,omitempty"`

	DatabaseName *string `json:"databaseName,omitempty"`

	Port *int64 `json:"port,omitempty"`

	SecretsManagerAccessRoleARN *string `json:"secretsManagerAccessRoleARN,omitempty"`

	SecretsManagerSecretID *string `json:"secretsManagerSecretID,omitempty"`

	ServerName *string `json:"serverName,omitempty"`

	Username *string `json:"username,omitempty"`
}

type MongoDBSettings struct {
	AuthSource *string `json:"authSource,omitempty"`

	DatabaseName *string `json:"databaseName,omitempty"`

	DocsToInvestigate *string `json:"docsToInvestigate,omitempty"`

	ExtractDocID *string `json:"extractDocID,omitempty"`

	KMSKeyID *string `json:"kmsKeyID,omitempty"`

	Port *int64 `json:"port,omitempty"`

	SecretsManagerAccessRoleARN *string `json:"secretsManagerAccessRoleARN,omitempty"`

	SecretsManagerSecretID *string `json:"secretsManagerSecretID,omitempty"`

	ServerName *string `json:"serverName,omitempty"`

	Username *string `json:"username,omitempty"`
}

type MySQLSettings struct {
	AfterConnectScript *string `json:"afterConnectScript,omitempty"`

	DatabaseName *string `json:"databaseName,omitempty"`

	EventsPollInterval *int64 `json:"eventsPollInterval,omitempty"`

	MaxFileSize *int64 `json:"maxFileSize,omitempty"`

	ParallelLoadThreads *int64 `json:"parallelLoadThreads,omitempty"`

	Port *int64 `json:"port,omitempty"`

	SecretsManagerAccessRoleARN *string `json:"secretsManagerAccessRoleARN,omitempty"`

	SecretsManagerSecretID *string `json:"secretsManagerSecretID,omitempty"`

	ServerName *string `json:"serverName,omitempty"`

	ServerTimezone *string `json:"serverTimezone,omitempty"`

	Username *string `json:"username,omitempty"`
}

type NeptuneSettings struct {
	ErrorRetryDuration *int64 `json:"errorRetryDuration,omitempty"`

	MaxFileSize *int64 `json:"maxFileSize,omitempty"`

	MaxRetryCount *int64 `json:"maxRetryCount,omitempty"`

	S3BucketFolder *string `json:"s3BucketFolder,omitempty"`

	S3BucketName *string `json:"s3BucketName,omitempty"`

	ServiceAccessRoleARN *string `json:"serviceAccessRoleARN,omitempty"`
}

type OracleSettings struct {
	AdditionalArchivedLogDestID *int64 `json:"additionalArchivedLogDestID,omitempty"`

	ArchivedLogDestID *int64 `json:"archivedLogDestID,omitempty"`

	AsmServer *string `json:"asmServer,omitempty"`

	AsmUser *string `json:"asmUser,omitempty"`

	DatabaseName *string `json:"databaseName,omitempty"`

	NumberDatatypeScale *int64 `json:"numberDatatypeScale,omitempty"`

	OraclePathPrefix *string `json:"oraclePathPrefix,omitempty"`

	ParallelAsmReadThreads *int64 `json:"parallelAsmReadThreads,omitempty"`

	Port *int64 `json:"port,omitempty"`

	ReadAheadBlocks *int64 `json:"readAheadBlocks,omitempty"`

	RetryInterval *int64 `json:"retryInterval,omitempty"`

	SecretsManagerAccessRoleARN *string `json:"secretsManagerAccessRoleARN,omitempty"`

	SecretsManagerOracleAsmAccessRoleARN *string `json:"secretsManagerOracleAsmAccessRoleARN,omitempty"`

	SecretsManagerOracleAsmSecretID *string `json:"secretsManagerOracleAsmSecretID,omitempty"`

	SecretsManagerSecretID *string `json:"secretsManagerSecretID,omitempty"`

	SecurityDBEncryptionName *string `json:"securityDBEncryptionName,omitempty"`

	ServerName *string `json:"serverName,omitempty"`

	UsePathPrefix *string `json:"usePathPrefix,omitempty"`

	Username *string `json:"username,omitempty"`
}

type OrderableReplicationInstance struct {
	EngineVersion *string `json:"engineVersion,omitempty"`

	ReplicationInstanceClass *string `json:"replicationInstanceClass,omitempty"`

	StorageType *string `json:"storageType,omitempty"`
}

type PendingMaintenanceAction struct {
	Action *string `json:"action,omitempty"`

	Description *string `json:"description,omitempty"`

	OptInStatus *string `json:"optInStatus,omitempty"`
}

type PostgreSQLSettings struct {
	AfterConnectScript *string `json:"afterConnectScript,omitempty"`

	DatabaseName *string `json:"databaseName,omitempty"`

	DdlArtifactsSchema *string `json:"ddlArtifactsSchema,omitempty"`

	ExecuteTimeout *int64 `json:"executeTimeout,omitempty"`

	MaxFileSize *int64 `json:"maxFileSize,omitempty"`

	Port *int64 `json:"port,omitempty"`

	SecretsManagerAccessRoleARN *string `json:"secretsManagerAccessRoleARN,omitempty"`

	SecretsManagerSecretID *string `json:"secretsManagerSecretID,omitempty"`

	ServerName *string `json:"serverName,omitempty"`

	SlotName *string `json:"slotName,omitempty"`

	Username *string `json:"username,omitempty"`
}

type RedshiftSettings struct {
	AfterConnectScript *string `json:"afterConnectScript,omitempty"`

	BucketFolder *string `json:"bucketFolder,omitempty"`

	BucketName *string `json:"bucketName,omitempty"`

	ConnectionTimeout *int64 `json:"connectionTimeout,omitempty"`

	DatabaseName *string `json:"databaseName,omitempty"`

	DateFormat *string `json:"dateFormat,omitempty"`

	FileTransferUploadStreams *int64 `json:"fileTransferUploadStreams,omitempty"`

	LoadTimeout *int64 `json:"loadTimeout,omitempty"`

	MaxFileSize *int64 `json:"maxFileSize,omitempty"`

	Port *int64 `json:"port,omitempty"`

	ReplaceChars *string `json:"replaceChars,omitempty"`

	ReplaceInvalidChars *string `json:"replaceInvalidChars,omitempty"`

	SecretsManagerAccessRoleARN *string `json:"secretsManagerAccessRoleARN,omitempty"`

	SecretsManagerSecretID *string `json:"secretsManagerSecretID,omitempty"`

	ServerName *string `json:"serverName,omitempty"`

	ServerSideEncryptionKMSKeyID *string `json:"serverSideEncryptionKMSKeyID,omitempty"`

	ServiceAccessRoleARN *string `json:"serviceAccessRoleARN,omitempty"`

	TimeFormat *string `json:"timeFormat,omitempty"`

	Username *string `json:"username,omitempty"`

	WriteBufferSize *int64 `json:"writeBufferSize,omitempty"`
}

type RefreshSchemasStatus struct {
	EndpointARN *string `json:"endpointARN,omitempty"`

	LastFailureMessage *string `json:"lastFailureMessage,omitempty"`

	ReplicationInstanceARN *string `json:"replicationInstanceARN,omitempty"`
}

type ReplicationInstance struct {
	AvailabilityZone *string `json:"availabilityZone,omitempty"`

	DNSNameServers *string `json:"dnsNameServers,omitempty"`

	EngineVersion *string `json:"engineVersion,omitempty"`

	KMSKeyID *string `json:"kmsKeyID,omitempty"`

	PreferredMaintenanceWindow *string `json:"preferredMaintenanceWindow,omitempty"`

	ReplicationInstanceARN *string `json:"replicationInstanceARN,omitempty"`

	ReplicationInstanceClass *string `json:"replicationInstanceClass,omitempty"`

	ReplicationInstanceIdentifier *string `json:"replicationInstanceIdentifier,omitempty"`

	ReplicationInstancePrivateIPAddress *string `json:"replicationInstancePrivateIPAddress,omitempty"`

	ReplicationInstancePublicIPAddress *string `json:"replicationInstancePublicIPAddress,omitempty"`

	ReplicationInstanceStatus *string `json:"replicationInstanceStatus,omitempty"`
	// Describes a subnet group in response to a request by the DescribeReplicationSubnetGroups
	// operation.
	ReplicationSubnetGroup *ReplicationSubnetGroup_SDK `json:"replicationSubnetGroup,omitempty"`

	SecondaryAvailabilityZone *string `json:"secondaryAvailabilityZone,omitempty"`
}

type ReplicationInstanceTaskLog struct {
	ReplicationTaskARN *string `json:"replicationTaskARN,omitempty"`

	ReplicationTaskName *string `json:"replicationTaskName,omitempty"`
}

type ReplicationPendingModifiedValues struct {
	AllocatedStorage *int64 `json:"allocatedStorage,omitempty"`

	EngineVersion *string `json:"engineVersion,omitempty"`

	ReplicationInstanceClass *string `json:"replicationInstanceClass,omitempty"`
}

type ReplicationSubnetGroup_SDK struct {
	ReplicationSubnetGroupDescription *string `json:"replicationSubnetGroupDescription,omitempty"`

	ReplicationSubnetGroupIdentifier *string `json:"replicationSubnetGroupIdentifier,omitempty"`

	SubnetGroupStatus *string `json:"subnetGroupStatus,omitempty"`

	Subnets []*Subnet `json:"subnets,omitempty"`

	VPCID *string `json:"vpcID,omitempty"`
}

type ReplicationTask struct {
	CdcStartPosition *string `json:"cdcStartPosition,omitempty"`

	CdcStopPosition *string `json:"cdcStopPosition,omitempty"`

	LastFailureMessage *string `json:"lastFailureMessage,omitempty"`

	RecoveryCheckpoint *string `json:"recoveryCheckpoint,omitempty"`

	ReplicationInstanceARN *string `json:"replicationInstanceARN,omitempty"`

	ReplicationTaskARN *string `json:"replicationTaskARN,omitempty"`

	ReplicationTaskIdentifier *string `json:"replicationTaskIdentifier,omitempty"`

	ReplicationTaskSettings *string `json:"replicationTaskSettings,omitempty"`

	SourceEndpointARN *string `json:"sourceEndpointARN,omitempty"`

	Status *string `json:"status,omitempty"`

	StopReason *string `json:"stopReason,omitempty"`

	TableMappings *string `json:"tableMappings,omitempty"`

	TargetEndpointARN *string `json:"targetEndpointARN,omitempty"`

	TargetReplicationInstanceARN *string `json:"targetReplicationInstanceARN,omitempty"`

	TaskData *string `json:"taskData,omitempty"`
}

type ReplicationTaskAssessmentResult struct {
	AssessmentResults *string `json:"assessmentResults,omitempty"`

	AssessmentResultsFile *string `json:"assessmentResultsFile,omitempty"`

	AssessmentStatus *string `json:"assessmentStatus,omitempty"`

	ReplicationTaskARN *string `json:"replicationTaskARN,omitempty"`

	ReplicationTaskIdentifier *string `json:"replicationTaskIdentifier,omitempty"`

	S3ObjectURL *string `json:"s3ObjectURL,omitempty"`
}

type ReplicationTaskAssessmentRun struct {
	AssessmentRunName *string `json:"assessmentRunName,omitempty"`

	LastFailureMessage *string `json:"lastFailureMessage,omitempty"`

	ReplicationTaskARN *string `json:"replicationTaskARN,omitempty"`

	ReplicationTaskAssessmentRunARN *string `json:"replicationTaskAssessmentRunARN,omitempty"`

	ResultEncryptionMode *string `json:"resultEncryptionMode,omitempty"`

	ResultKMSKeyARN *string `json:"resultKMSKeyARN,omitempty"`

	ResultLocationBucket *string `json:"resultLocationBucket,omitempty"`

	ResultLocationFolder *string `json:"resultLocationFolder,omitempty"`

	ServiceAccessRoleARN *string `json:"serviceAccessRoleARN,omitempty"`

	Status *string `json:"status,omitempty"`
}

type ReplicationTaskIndividualAssessment struct {
	IndividualAssessmentName *string `json:"individualAssessmentName,omitempty"`

	ReplicationTaskAssessmentRunARN *string `json:"replicationTaskAssessmentRunARN,omitempty"`

	ReplicationTaskIndividualAssessmentARN *string `json:"replicationTaskIndividualAssessmentARN,omitempty"`

	Status *string `json:"status,omitempty"`
}

type ResourcePendingMaintenanceActions struct {
	ResourceIdentifier *string `json:"resourceIdentifier,omitempty"`
}

type S3Settings struct {
	BucketFolder *string `json:"bucketFolder,omitempty"`

	BucketName *string `json:"bucketName,omitempty"`

	CdcPath *string `json:"cdcPath,omitempty"`

	CsvDelimiter *string `json:"csvDelimiter,omitempty"`

	CsvNoSupValue *string `json:"csvNoSupValue,omitempty"`

	CsvRowDelimiter *string `json:"csvRowDelimiter,omitempty"`

	DataPageSize *int64 `json:"dataPageSize,omitempty"`

	DictPageSizeLimit *int64 `json:"dictPageSizeLimit,omitempty"`

	ExternalTableDefinition *string `json:"externalTableDefinition,omitempty"`

	RowGroupLength *int64 `json:"rowGroupLength,omitempty"`

	ServerSideEncryptionKMSKeyID *string `json:"serverSideEncryptionKMSKeyID,omitempty"`

	ServiceAccessRoleARN *string `json:"serviceAccessRoleARN,omitempty"`

	TimestampColumnName *string `json:"timestampColumnName,omitempty"`
}

type Subnet struct {
	// The name of an Availability Zone for use during database migration. AvailabilityZone
	// is an optional parameter to the CreateReplicationInstance (https://docs.aws.amazon.com/dms/latest/APIReference/API_CreateReplicationInstance.html)
	// operation, and it’s value relates to the AWS Region of an endpoint. For
	// example, the availability zone of an endpoint in the us-east-1 region might
	// be us-east-1a, us-east-1b, us-east-1c, or us-east-1d.
	SubnetAvailabilityZone *AvailabilityZone `json:"subnetAvailabilityZone,omitempty"`

	SubnetIdentifier *string `json:"subnetIdentifier,omitempty"`

	SubnetStatus *string `json:"subnetStatus,omitempty"`
}

type SupportedEndpointType struct {
	EngineDisplayName *string `json:"engineDisplayName,omitempty"`

	EngineName *string `json:"engineName,omitempty"`

	ReplicationInstanceEngineMinimumVersion *string `json:"replicationInstanceEngineMinimumVersion,omitempty"`
}

type SybaseSettings struct {
	DatabaseName *string `json:"databaseName,omitempty"`

	Port *int64 `json:"port,omitempty"`

	SecretsManagerAccessRoleARN *string `json:"secretsManagerAccessRoleARN,omitempty"`

	SecretsManagerSecretID *string `json:"secretsManagerSecretID,omitempty"`

	ServerName *string `json:"serverName,omitempty"`

	Username *string `json:"username,omitempty"`
}

type TableStatistics struct {
	SchemaName *string `json:"schemaName,omitempty"`

	TableName *string `json:"tableName,omitempty"`

	TableState *string `json:"tableState,omitempty"`

	ValidationState *string `json:"validationState,omitempty"`

	ValidationStateDetails *string `json:"validationStateDetails,omitempty"`
}

type TableToReload struct {
	SchemaName *string `json:"schemaName,omitempty"`

	TableName *string `json:"tableName,omitempty"`
}

type Tag struct {
	Key *string `json:"key,omitempty"`

	Value *string `json:"value,omitempty"`
}

type VPCSecurityGroupMembership struct {
	Status *string `json:"status,omitempty"`

	VPCSecurityGroupID *string `json:"vpcSecurityGroupID,omitempty"`
}
